version: "1.0"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: ${MONGO_URI}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      # 80 is the default port Nginx serves, mapped to 3000
      - "3000:80"
    environment:
      VITE_BACKEND_URL: "http://localhost:5000"
